name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Restore .NET Tools
        run: dotnet tool restore || echo "No tools to restore."

      # Authenticate with Docker Hub using Personal Access Token
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Setup Testcontainers Cloud
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      
      - name: Verify Testcontainers Cloud Status
        run: |
          echo "Checking available Docker contexts..."
          docker context ls
          echo "Waiting for Testcontainers Cloud to be ready..."
          sleep 10
          echo "Switching to Testcontainers Cloud context..."
          for i in {1..5}; do
            docker context use tcc && break || sleep 5
          done
          echo "Current Docker info:"
          for i in {1..5}; do
            docker info && break || (echo "Retrying in 5s..." && sleep 5)
          done

      # Wait for Testcontainers Cloud to fully initialize
      - name: Wait for Testcontainers Cloud to Initialize
        run: sleep 15

      # Retry Context Switching
      - name: Retry Testcontainers Cloud Context Switch
        run: |
          for i in {1..5}; do
            docker context use tcc && break || sleep 5
          done

      # Check Docker Info
      - name: Verify Docker Context
        run: docker info || exit 1

      # Run tests
      - name: Run Tests with Testcontainers Cloud
        run: |
          docker context use tcc
          make test
