name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Verify Docker Context
        run: |
          echo "Checking available Docker contexts..."
          docker context ls
          echo "Switching to Testcontainers Cloud context..."
          docker context use tcc || exit 1
          echo "Current Docker info:"
          docker info

      - name: Enable Testcontainers Debug Logs
        run: |
          echo "Enabling Testcontainers debug logs..."
          echo "TESTCONTAINERS_RYUK_DISABLED=false" >> $GITHUB_ENV
          echo "TESTCONTAINERS_LOG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Run tests
        run: make test
