name: Test Docker Image

on:
  push:
    branches: [ main ]  # Run workflow on push to main branch

jobs:
  test-existing-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Setup Testcontainers Cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Change to project directory
        run: cd tests

      - name: Run Tests using Testcontainers
        run: dotnet test --logger:"console;verbosity=detailed"

