name: Testcontainers Cloud Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install Testcontainers Cloud
        run: |
          set -e  # Exit immediately on error
          
          echo "Checking DNS resolution for Testcontainers Cloud..."
          if ! nslookup download.testcontainers.cloud > /dev/null 2>&1; then
            echo "❌ Could not resolve host: download.testcontainers.cloud"
          fi

          echo "Attempting to download Testcontainers Cloud..."
          if curl -fsSL https://download.testcontainers.cloud/testcontainers-cloud-linux -o install-tc.sh; then
            echo "✅ Download successful via curl!"
          elif wget -q https://download.testcontainers.cloud/testcontainers-cloud-linux -O install-tc.sh; then
            echo "✅ Download successful via wget!"
          else
            echo "❌ Primary and fallback downloads failed! Trying alternative method..."
            if curl -fsSL https://get.testcontainers.cloud | bash; then
              echo "✅ Installed via alternative method!"
              exit 0
            else
              echo "❌ All installation methods failed! Exiting..."
              exit 1
            fi
          fi

          chmod +x install-tc.sh
          ./install-tc.sh

      - name: Start Testcontainers Cloud Agent
        run: |
          echo "Starting Testcontainers Cloud agent..."
          testcontainers-cloud &  # Start agent in background
          sleep 5  # Wait for agent to initialize

          if ! testcontainers-cloud --status; then
            echo "❌ Testcontainers Cloud agent failed to start!"
            exit 1
          fi
          echo "✅ Testcontainers Cloud agent is running."

      - name: Set Docker Context to Testcontainers Cloud
        run: |
          echo "Setting Docker context to Testcontainers Cloud..."
          docker context use tcc || { echo "❌ Testcontainers Cloud context not available!"; exit 1; }
          docker context ls

      - name: Verify Docker is Running
        run: |
          if ! docker ps > /dev/null 2>&1; then
            echo "❌ Docker is not running! Exiting..."
            exit 1
          fi
          echo "✅ Docker is running."

      - name: List Running Docker Containers
        run: docker ps -a

      - name: Run Tests with Testcontainers Cloud
        run: |
          echo "Running tests..."
          cd tests
          dotnet test --logger:"console;verbosity=detailed"
