name: Test Docker Image

on:
  push:
    branches: [ main ]

jobs:
  test-existing-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Setup Testcontainers Cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Force Testcontainers Cloud as Docker context
        run: docker context use tcc

      - name: Debug Docker Context
        run: docker context ls

      - name: Check if Testcontainers Cloud Agent is running
        run: ps aux | grep testcontainers | grep -v grep || echo "Testcontainers Cloud agent is not running!"

      - name: Change to project directory
        run: cd tests

      - name: Run Tests using Testcontainers
        run: dotnet test --logger:"console;verbosity=detailed"
        env:
          DOCKER_HOST: "tcp://127.0.0.1:38307"  # Update based on docker context ls output
