name: Testcontainers Cloud Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Check DNS Resolution for Testcontainers Cloud
        run: |
          nslookup download.testcontainers.cloud || echo "❌ DNS lookup failed!"
          ping -c 4 download.testcontainers.cloud || echo "❌ Ping failed!"

      - name: Attempt to Download Testcontainers Cloud
        run: |
          echo "Downloading Testcontainers Cloud..."
          curl -fsSL -o testcontainers-cloud https://download.testcontainers.cloud/testcontainers-cloud-linux
          chmod +x testcontainers-cloud
          mv testcontainers-cloud $HOME/.testcontainers/bin/
          export PATH="$HOME/.testcontainers/bin:$PATH"
          echo "export PATH=\"$HOME/.testcontainers/bin:\$PATH\"" >> $HOME/.bashrc
          source $HOME/.bashrc
        continue-on-error: true  # Allow failure and try alternative method

      - name: Verify Downloaded File (First 20 Lines)
        run: |
          head -n 20 $HOME/.testcontainers/bin/testcontainers-cloud || echo "❌ File not found!"

      - name: Fallback: Run Testcontainers via Docker if Install Fails
        if: failure()
        run: |
          echo "⚠️ Testcontainers Cloud download failed. Using Docker instead."
          docker pull testcontainers/ryuk
          docker run --rm testcontainers/ryuk

      - name: Start Testcontainers Cloud Agent
        run: |
          testcontainers-cloud &  # Start agent in background
          sleep 5  # Wait for the agent to initialize
          testcontainers-cloud --status || echo "❌ Testcontainers Cloud agent failed to start!"

      - name: Set Docker Context to Testcontainers Cloud
        run: |
          docker context use tcc || echo "❌ Testcontainers Cloud context not available!"
          docker context ls

      - name: List Running Docker Containers
        run: docker ps -a

      - name: Run Tests with Testcontainers Cloud
        run: |
          cd tests
          dotnet test --logger:"console;verbosity=detailed"
